### ISSUE TITLE
neovim support?

### ISSUE THREAD

**Issue by davidosomething** [cocopon/colorswatch.vim#2]
any way to get this working for neovim?
Currently only get the 256color code for the base2tone-Lake-Dark colorscheme

**Comment by cocopon** [comment]
Added support for true color terminal.

It works correctly in my environment:
- macOS 10.11.3
- iTerm 3.0.10
- neovim 0.1.5 with `termguicolors` option

Is the problem solved?

**Comment by davidosomething** [comment]
solved! thanks!
